# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 17:55
from __future__ import unicode_literals

from django.db import migrations

from hep_app.models import SkiStats


def add_ski_data(apps, schema_editor):
    SkiStats.objects.create(rank=1, athlete='Marina Kiehl', age=23, team='WGermany', noc='FRG', medal='Gold',
                           t_time='85.86')
    SkiStats.objects.create(rank=2, athlete='Brigitte Oertli', age=25, team='Switzerland', noc='SUI', medal='Silver',
                           t_time='86.61')
    SkiStats.objects.create(rank=3, athlete='Karen Percy', age=21, team='Canada', noc='CAN', medal='Bronze',
                           t_time='86.62')
    SkiStats.objects.create(rank=4, athlete='Maria Walliser', age=24, team='Switzerland', noc='SUI', medal='None',
                           t_time='86.89')
    SkiStats.objects.create(rank=5, athlete='Laurie Graham', age=27, team='Canada', noc='CAN', medal='None',
                           t_time='86.99')
    SkiStats.objects.create(rank=6, athlete='Petra Kronberger', age=18, team='Austria', noc='AUT', medal='None',
                           t_time='87.03')
    SkiStats.objects.create(rank=7, athlete='Regine Mosenlechner', age=26, team='WGermany', noc='FRG', medal='None',
                           t_time='87.16')
    SkiStats.objects.create(rank=8, athlete='Lisi Kirchler', age=24, team='Austria', noc='AUT', medal='None',
                           t_time='87.19')
    SkiStats.objects.create(rank=9, athlete='Michela Figini', age=21, team='Switzerland', noc='SUI', medal='None',
                           t_time='87.26')
    SkiStats.objects.create(rank=10, athlete='Lucia Medzihradsk', age=19, team='Czechoslovakia', noc='TCH', medal='None',
                           t_time='87.28')


class Migration(migrations.Migration):

    dependencies = [
        ('hep_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_ski_data)
    ]
